### ISSUE TITLE
Criar layout base para criação das páginas

### ISSUE THREAD

**Issue by gabrieldev525** [gabrieldev525/site-algoritmos-fundamentais#7]
Deve ser criado um layout que será usado em todas as páginas do site. Com isso, reduzirá significamente a quantidade de códigos e facilitará a criação e manutenção das páginas futuras.

Deve ser utilizado os layouts do EJS

**Comment by Heldercmj** [comment]
https://github.com/gabrieldev525/site-algoritmos-fundamentais/pull/8
